import type { Metadata } from "next";
import { Urbanist } from 'next/font/google'
import "./globals.css";

const urbanist = Urbanist({
  subsets: ['latin'],       // yoki ['latin', 'cyrillic'] agar kerak bo‘lsa
  weight: ['400', '600', '700'], // kerakli font og‘irliklari
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
